package practicapeliculas;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.io.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.util.HashSet;


public class VentanaDatos extends javax.swing.JFrame {
    Peliculas films = new Peliculas();
    Usuarios users = new Usuarios(films);
    /**
     * Creates new form VentanaDatos
     */
    public VentanaDatos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombreUsuario = new javax.swing.JTextField();
        bIniciarSesion = new javax.swing.JButton();
        bRegistrarse = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        campoPass = new javax.swing.JPasswordField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        botonGuardarPeliculas = new javax.swing.JMenuItem();
        botonCargarPeliculas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre de usuario:");

        jLabel2.setText("Contraseña:");

        nombreUsuario.setName(""); // NOI18N

        bIniciarSesion.setText("Iniciar Sesión");
        bIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIniciarSesionActionPerformed(evt);
            }
        });

        bRegistrarse.setText("Registrarse");
        bRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegistrarseActionPerformed(evt);
            }
        });

        jLabel3.setText("                          ");

        jMenu1.setText("Archivo");

        botonGuardarPeliculas.setText("Guardar sistema...");
        botonGuardarPeliculas.setToolTipText("");
        botonGuardarPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarPeliculasActionPerformed(evt);
            }
        });
        jMenu1.add(botonGuardarPeliculas);

        botonCargarPeliculas.setText("Cargar sistema...");
        botonCargarPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarPeliculasActionPerformed(evt);
            }
        });
        jMenu1.add(botonCargarPeliculas);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1)
                        .addGap(39, 39, 39)
                        .addComponent(nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel2)
                        .addGap(81, 81, 81)
                        .addComponent(campoPass, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(bIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(bRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel3)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1))
                    .addComponent(nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2))
                    .addComponent(campoPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(bIniciarSesion)
                .addGap(6, 6, 6)
                .addComponent(bRegistrarse)
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIniciarSesionActionPerformed
        // TODO add your handling code here:
        char[] pass_ = campoPass.getPassword();
        String clave = new String(pass_);
        Usuario usu = users.buscarUsuario(nombreUsuario.getText());
        if (!(nombreUsuario.getText().length() > 0) && (clave.length() > 0)) {
            camposVacios();
        }
        else if(users.existe(nombreUsuario.getText()) && usu.getContrasena().equals(clave)){  
            VentanaPrincipal ventanaPrincipal = new VentanaPrincipal();
            ventanaPrincipal.setUser(usu);
            ventanaPrincipal.setUsers(users);
            ventanaPrincipal.setFilms(films);
            ventanaPrincipal.setTextoMuro(usu.getMuro());
            ventanaPrincipal.setVisible(true);
            this.setVisible(false);
        }else{
            campoIncorrecto();
        }
        
    }//GEN-LAST:event_bIniciarSesionActionPerformed

    private void bRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegistrarseActionPerformed
        // TODO add your handling code here:
        char[] pass_ = campoPass.getPassword();
        String clave = new String(pass_);
        if(users.existe(nombreUsuario.getText())){
            msgUsuarioExistente();
        }
        else if((nombreUsuario.getText().length() > 0) && (clave.length() > 0)){
            users.registrar(new Usuario(nombreUsuario.getText(), clave, users, films));
            JOptionPane.showMessageDialog(this, "Te has registrado correctamente. Inicia sesión para comenzar.", "Registro con éxito", JOptionPane.INFORMATION_MESSAGE);
        }else{
            camposVacios();
        }
        
    }//GEN-LAST:event_bRegistrarseActionPerformed

    private void botonGuardarPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarPeliculasActionPerformed

        JFileChooser selectorArchivos = new JFileChooser();
        selectorArchivos.addChoosableFileFilter(new FileNameExtensionFilter("Archivos binarios (.bin)", "bin", "BIN"));     // asi se pueden filtrar los archivos.bin
        selectorArchivos.setAcceptAllFileFilterUsed(false);     
        int opcionSeleccionada = selectorArchivos.showSaveDialog(this);
        if(opcionSeleccionada == JFileChooser.APPROVE_OPTION ){
            try{
                File archivo = selectorArchivos.getSelectedFile();
                String ruta = archivo.getAbsolutePath();
                if(!ruta.endsWith(".bin")){
                    ruta += ".bin";     // si el usuario no ha puesto la extension .bin, se escribe automaticamente
                }
                FileOutputStream file = new FileOutputStream(ruta);
                ObjectOutputStream outStream = new ObjectOutputStream(file);
                outStream.writeObject(users.getListaUsuarios());
                outStream.writeObject(films.getListaPeliculas());
                outStream.close();
                JOptionPane.showMessageDialog(this, "Se ha guardado el archivo " + ruta + " correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            }catch(IOException ex){
                JOptionPane.showMessageDialog(this, "Se ha producido un error al guardar el archivo.", "Error", JOptionPane.ERROR_MESSAGE);
            }            
        }
    }//GEN-LAST:event_botonGuardarPeliculasActionPerformed

    private void botonCargarPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarPeliculasActionPerformed

        JFileChooser selectorArchivos = new JFileChooser();
        selectorArchivos.addChoosableFileFilter(new FileNameExtensionFilter("Archivos binarios (.bin)", "bin", "BIN"));     // asi se pueden filtrar los archivos.bin
        selectorArchivos.setAcceptAllFileFilterUsed(false);
        int opcionSeleccionada = selectorArchivos.showOpenDialog(this);
        if (opcionSeleccionada == JFileChooser.APPROVE_OPTION) {
            try {
                File archivo = selectorArchivos.getSelectedFile();
                FileInputStream file = new FileInputStream(archivo);
                ObjectInputStream inputStream = new ObjectInputStream(file);
                users.setListaUsuarios((HashSet<Usuario>) inputStream.readObject());
                films.setListaPeliculas((HashSet<Pelicula>) inputStream.readObject());
                inputStream.close();
                JOptionPane.showMessageDialog(this, "Se ha cargado el archivo correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Se ha producido un error al cargar el archivo.", "Error", JOptionPane.ERROR_MESSAGE);
            } catch (ClassNotFoundException ex){
                JOptionPane.showMessageDialog(this, "Se ha producido un error al cargar el archivo.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_botonCargarPeliculasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaDatos().setVisible(true);
            }
        });
    }
    
    public void camposVacios(){
        JOptionPane.showMessageDialog(this, "Te has dejado uno de los campos vacíos. Inténtalo de nuevo.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    public void campoIncorrecto(){
        JOptionPane.showMessageDialog(this, "Nombre de usuario o contraseña incorrecto(s).", "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    public void msgUsuarioExistente() {
        JOptionPane.showMessageDialog(this, "El nombre de usuario introducido ya está en uso.", "Error", JOptionPane.ERROR_MESSAGE);
    }

    public void setUsers(Usuarios users) {
        this.users = users;
    }

    public void setFilms(Peliculas films) {
        this.films = films;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bIniciarSesion;
    private javax.swing.JButton bRegistrarse;
    private javax.swing.JMenuItem botonCargarPeliculas;
    private javax.swing.JMenuItem botonGuardarPeliculas;
    private javax.swing.JPasswordField campoPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField nombreUsuario;
    // End of variables declaration//GEN-END:variables
}
