/**
 * Ultima actualizacion: 30/12/2018
 * Cambios: (Por Carlos Sánchez Muñoz) Se puede Iniciar Sesión y Registrar usuarios
 * Version:1 
 *
 */
package practicapeliculas;

import javax.swing.JOptionPane;

/**
 *
 * @author carlo
 */
public class VentanaDatos extends javax.swing.JFrame {
    Peliculas films = new Peliculas();
    Usuarios users = new Usuarios(films);
    /**
     * Creates new form VentanaDatos
     */
    public VentanaDatos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombreUsuario = new javax.swing.JTextField();
        bIniciarSesion = new javax.swing.JButton();
        bRegistrarse = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        campoPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Nombre de usuario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(73, 68, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setText("Contraseña:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 68, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        nombreUsuario.setName(""); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 106;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(69, 39, 0, 85);
        getContentPane().add(nombreUsuario, gridBagConstraints);

        bIniciarSesion.setText("Iniciar Sesión");
        bIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIniciarSesionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(44, 2, 0, 0);
        getContentPane().add(bIniciarSesion, gridBagConstraints);

        bRegistrarse.setText("Registrarse");
        bRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegistrarseActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 2, 0, 0);
        getContentPane().add(bRegistrarse, gridBagConstraints);

        jLabel3.setText("                          ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 10, 32, 0);
        getContentPane().add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 106;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 39, 0, 85);
        getContentPane().add(campoPass, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIniciarSesionActionPerformed
        // TODO add your handling code here:
        char[] pass_ = campoPass.getPassword();
        String clave = new String(pass_);
        Usuario usu = users.buscarUsuario(nombreUsuario.getText());
        if (!(nombreUsuario.getText().length() > 0) && (clave.length() > 0)) {
            camposVacios();
        }
        else if(users.existe(nombreUsuario.getText()) && usu.getContrasena().equals(clave)){  
            VentanaPrincipal ventanaPrincipal = new VentanaPrincipal();
            ventanaPrincipal.setUser(usu);
            ventanaPrincipal.setUsers(users);
            ventanaPrincipal.setFilms(films);
            ventanaPrincipal.setTextoMuro(usu.getMuro());
            ventanaPrincipal.setVisible(true);
            this.setVisible(false);
        }else{
            campoIncorrecto();
        }
        
    }//GEN-LAST:event_bIniciarSesionActionPerformed

    private void bRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegistrarseActionPerformed
        // TODO add your handling code here:
        char[] pass_ = campoPass.getPassword();
        String clave = new String(pass_);
        if(users.existe(nombreUsuario.getText())){
            msgUsuarioExistente();
        }
        else if((nombreUsuario.getText().length() > 0) && (clave.length() > 0)){
            users.getListaUsuarios().add(new Usuario(nombreUsuario.getText(), clave, users, films));
            JOptionPane.showMessageDialog(this, "Te has registrado correctamente. Inicia sesión para comenzar.", "Registro con éxito", JOptionPane.INFORMATION_MESSAGE);
        }else{
            camposVacios();
        }
        
    }//GEN-LAST:event_bRegistrarseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaDatos().setVisible(true);
            }
        });
    }
    
    public void camposVacios(){
        JOptionPane.showMessageDialog(this, "Te has dejado uno de los campos vacíos. Inténtalo de nuevo.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    public void campoIncorrecto(){
        JOptionPane.showMessageDialog(this, "Nombre de usuario o contraseña incorrecto(s).", "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    public void msgUsuarioExistente() {
        JOptionPane.showMessageDialog(this, "El nombre de usuario introducido ya está en uso.", "Error", JOptionPane.ERROR_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bIniciarSesion;
    private javax.swing.JButton bRegistrarse;
    private javax.swing.JPasswordField campoPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nombreUsuario;
    // End of variables declaration//GEN-END:variables
}
