/*
 * Ultima actualizacion: 03/01/2019
 * Cambios: 
 * Version:1
 */
package practicapeliculas;

import javax.swing.JComboBox;
import java.util.Iterator;




/**
 *
 * @author Mario
 */
public class VentanaListaAmigos extends javax.swing.JFrame {

    private Usuario user;
    /**
     * Creates new form VentanaListaAmigos
     */
    public VentanaListaAmigos() {
        initComponents();
        
    }
    public void setjComboLAmigos(String amigo){
        jComboLAmigos.addItem(amigo);
        
    }

    public JComboBox<String> getjComboLAmigos() {
        return jComboLAmigos;
    }
    
    public void setuser(Usuario u){
        this.user = u;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboLAmigos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jBotonVerAmigo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboLAmigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboLAmigosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Amigos");

        jBotonVerAmigo.setText("Ver amigo");
        jBotonVerAmigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonVerAmigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jBotonVerAmigo)
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboLAmigos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jComboLAmigos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBotonVerAmigo)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBotonVerAmigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonVerAmigoActionPerformed
        Iterator<Usuario> i = user.getLista_amigos().iterator();
        Usuario amigo = new Usuario();
        Usuario aux = new Usuario();
        Object name = "";
        name = jComboLAmigos.getSelectedItem();
        
        while(i.hasNext()){//Iterator para buscar en la lista de amigos cual es el que se ha seleccionado 
            aux = i.next();
            if (aux.getNombre().equals(name)){
                amigo = aux;
            }
        }
        VentanaAmigo vAmigo = new VentanaAmigo();
        vAmigo.getjLabelNombreAmigo().setText("Muro de " + amigo.getNombre());
        vAmigo.getjLabelMuroAmigo().setText(amigo.getMuro().toString());
        vAmigo.setVisible(true);
        
        
        
    }//GEN-LAST:event_jBotonVerAmigoActionPerformed

    private void jComboLAmigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboLAmigosActionPerformed
        
    }//GEN-LAST:event_jComboLAmigosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaListaAmigos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaListaAmigos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaListaAmigos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaListaAmigos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaListaAmigos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBotonVerAmigo;
    private javax.swing.JComboBox<String> jComboLAmigos;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
