/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicapeliculas;

import javax.swing.JOptionPane;

/**
 *
 * @author carlo
 */
public class VentanaPreguntas extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPreguntas
     */
    
    private Partida partida;
    private Pregunta pregunta;
    private Pregunta[] listaPreguntas;
    private int contadorPistas = 0;
    private int contadorPreguntas = 0;     // el contador siempre tiene un valor menos del que realmente tendría para tener en cuenta el rango del array (0-5)
    private String pistas;
    private int puntosActuales = 50;
    private int puntosTotales = 0;
    private Usuario jugador;
    
    public VentanaPreguntas() {
        initComponents();
        //pregunta = listaPreguntas[1].toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        preguntaNumero = new javax.swing.JLabel();
        textoRespuesta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoPistas = new javax.swing.JTextArea();
        textoPregunta = new javax.swing.JLabel();
        bResponder = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        preguntaNumero.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        preguntaNumero.setText("Pregunta " + contadorPreguntas + 1);

        textoRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoRespuestaActionPerformed(evt);
            }
        });

        textoPistas.setEditable(false);
        textoPistas.setBackground(new java.awt.Color(255, 255, 255));
        textoPistas.setColumns(20);
        textoPistas.setForeground(new java.awt.Color(255, 255, 255));
        textoPistas.setLineWrap(true);
        textoPistas.setRows(5);
        textoPistas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        textoPistas.setOpaque(false);
        jScrollPane1.setViewportView(textoPistas);

        textoPregunta.setText("<pregunta>");

        bResponder.setText("Responder");
        bResponder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResponderActionPerformed(evt);
            }
        });

        jLabel1.setText("Pistas:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(bResponder)
                    .addComponent(preguntaNumero)
                    .addComponent(textoPregunta)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addComponent(preguntaNumero)
                .addGap(18, 18, 18)
                .addComponent(textoPregunta)
                .addGap(37, 37, 37)
                .addComponent(textoRespuesta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bResponder)
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bResponderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResponderActionPerformed
        // TODO add your handling code here:
        if (pregunta.comprobarRespuesta(textoRespuesta.getText())) {
            JOptionPane.showMessageDialog(this, "¡Respuesta correcta! +" + puntosActuales + " puntos", "Respuesta correcta", JOptionPane.PLAIN_MESSAGE);
            puntosTotales += puntosActuales;
            if(contadorPreguntas == 6){
                finalizar();
            }else{
                ofrecerNuevaPregunta();
            }

        } else {
            JOptionPane.showMessageDialog(this, "¡Respuesta incorrecta!", "Respuesta correcta", JOptionPane.PLAIN_MESSAGE);
            contadorPistas++;
            if(contadorPistas < 5){
                pistas += "\r\n" + pregunta.ofrecerNuevaPista();
                textoPistas.setText(pistas);
                puntosActuales -= 10;
            }
        }

        if (contadorPistas > 4 && contadorPreguntas < 6){
            ofrecerNuevaPregunta();
        }
        else if(contadorPistas > 4 && contadorPreguntas == 6){
            finalizar();
            // prueba blablabla

        }

    }//GEN-LAST:event_bResponderActionPerformed

    private void textoRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoRespuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoRespuestaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPreguntas().setVisible(true);
                
            }
        });
    }

    public void setPartida(Partida partida) {
        this.partida = partida;
    }

    public void inicializar() {
        ofrecerNuevaPregunta();
    }

    public void setListaPreguntas(Pregunta[] listaPreguntas) {
        this.listaPreguntas = listaPreguntas;
    }

    public void setJugador(Usuario jugador) {
        this.jugador = jugador;
    }
    
    public void ofrecerNuevaPregunta(){       
        preguntaNumero.setText("Pregunta " + (contadorPreguntas + 1));
        pregunta = listaPreguntas[contadorPreguntas];
        textoPregunta.setText(pregunta.toString());
        contadorPistas = 0;
        contadorPreguntas++;
        pistas = "";
        // Del alfabeto no se pero me puedes editar esta
        
    }
    
    public void finalizar(){
        if (jugador.equals(partida.getJ1())) {
            partida.setPtos_jugador1(puntosActuales);
            partida.ponerEnPendientes();
            JOptionPane.showMessageDialog(this, "¡Todas las preguntas completadas!\nHas ganado un total de " + puntosTotales + " puntos. \nQueda pendiente que el contrincante responda sus preguntas para conocer el resultado.", "Preguntas completadas", JOptionPane.PLAIN_MESSAGE);
        } else if (jugador.equals(partida.getJ2())) {
            partida.setPtos_jugador2(puntosActuales);
            partida.finalizarPartida();
            JOptionPane.showMessageDialog(this, "¡Todas las preguntas completadas!\nHas ganado un total de " + puntosTotales + " puntos. \nResultado:\n" + partida.toString(), "Partida completada", JOptionPane.PLAIN_MESSAGE);
        }

        this.setVisible(false);
        this.dispose();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bResponder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel preguntaNumero;
    private javax.swing.JTextArea textoPistas;
    private javax.swing.JLabel textoPregunta;
    private javax.swing.JTextField textoRespuesta;
    // End of variables declaration//GEN-END:variables
}
