/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicapeliculas;
import java.util.Iterator; 
/**
 *
 * @author Lidia
 */
public class VentanaPeliculas extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPeliculas
     */
    private Peliculas films; 
    private Pelicula film; 
    private Usuario user; 
    private Usuarios users; 
    
    public VentanaPeliculas() {
        initComponents();
    }
    
    public void setFilms(Peliculas films){
        this.films = films;
        // Recorrido iterator hashset
        Iterator<Pelicula> i = films.getListaPeliculas().iterator();  
        while (i.hasNext()){
            ComboPelis.addItem(i.next().getTitulo());// Asi salen los titulos en el combobox
        }
    }
    
    public void setUser(Usuario u){
        this.user = u; 
    }
    
    public void setUsers(Usuarios users){
       this.users = users; 
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ComboPelis = new javax.swing.JComboBox<>();
        BCompartir = new javax.swing.JButton();
        BCritica = new javax.swing.JButton();
        BVerpeli = new javax.swing.JButton();
        BAnadirpeli = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("PELICULAS");

        ComboPelis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboPelisActionPerformed(evt);
            }
        });

        BCompartir.setText("Compartir...");

        BCritica.setText("Realizar crítica");
        BCritica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCriticaActionPerformed(evt);
            }
        });

        BVerpeli.setText("Ver");
        BVerpeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BVerpeliActionPerformed(evt);
            }
        });

        BAnadirpeli.setText("Añadir pelicula");
        BAnadirpeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAnadirpeliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BVerpeli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BCompartir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BCritica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComboPelis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(BAnadirpeli)
                .addGap(36, 36, 36))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(ComboPelis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BCompartir)
                        .addGap(18, 18, 18)
                        .addComponent(BCritica)
                        .addGap(18, 18, 18)
                        .addComponent(BVerpeli))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BAnadirpeli, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboPelisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboPelisActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_ComboPelisActionPerformed

    private void BAnadirpeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAnadirpeliActionPerformed
        // TODO add your handling code here:
        VentanaPelicula ventanaP = new VentanaPelicula(); 
        ventanaP.setFilms(films); 
        ventanaP.setVisible(true); 
        this.setVisible(false); // Hacemos visible la nueva ventana y esta desaparece
    }//GEN-LAST:event_BAnadirpeliActionPerformed

    private void BCriticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCriticaActionPerformed
        // TODO add your handling code here:
        Pelicula p = films.buscarPelicula((String)ComboPelis.getSelectedItem()); 
        VentanaEscribeCr vEscribeC = new VentanaEscribeCr(); 
        vEscribeC.setFilm(p); 
        vEscribeC.setVisible(true); 
        this.setVisible(false);
    }//GEN-LAST:event_BCriticaActionPerformed

    private void BVerpeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BVerpeliActionPerformed
        // TODO add your handling code here:
        Pelicula p = films.buscarPelicula((String)ComboPelis.getSelectedItem()); 
        VentanaVerPeli ventanaV = new VentanaVerPeli(); 
        ventanaV.setFilm(p); // COMBOBOX 
        ventanaV.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_BVerpeliActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPeliculas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAnadirpeli;
    private javax.swing.JButton BCompartir;
    private javax.swing.JButton BCritica;
    private javax.swing.JButton BVerpeli;
    private javax.swing.JComboBox<String> ComboPelis;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
